### PR TITLE
Fix non unique Prefer header in Component Object

### LINKED ISSUE #26: Repeated "Prefer" header overrides the previous one in SwaggerUI
I had the idea to repeat the `Prefer` header for each preference that PostgREST has (count, tx, etc.). This would be useful to allow more than one Prefer Header at a time (which is not possible right now in the core repo).

But in SwaggerUI, the other Prefer headers are overridden and have the same value as the first one (since they all have the same `name: Prefer`). A solution would be to just add the valid transactions in the description e.g. "Valid values are: `tx=commit`, `return=minimal`, `...`" or find if it's possible to allow many `enum`s (couldn't find a way yet).

This is the relevant function:
https://github.com/PostgREST/postgrest-openapi/blob/81f5b64ac967e9ba9d4dace6e8fc0a56993b5d1d/sql/postgrest.sql#L615

### PR DESCRIPTION
**Pull request by laurenceisla**
Closes #26

Changes done to fix repeating the Prefer header:
- Define a Schema Object for each Preference
- Define a Parameter Object for each HTTP method that references only the relevant preferences

### CODE REVIEW

File: sql/components.sql [hunk 1]
```diff
@@ -51,6 +52,122 @@ FROM (
...
+    type := 'object',
+    properties := jsonb_build_object(
+      'params',
+      oas_schema_object(
+        description := 'Send JSON as a single parameter',
+        type := 'string',
+        "enum" := '["single-object"]'
+      )
+    )
+  ),
```
Comment (steve-chavez) [inline sql/components.sql:70]: Could we mark this as deprecated?

https://stackoverflow.com/questions/49870109/how-to-annotate-a-field-as-deprecated-in-openapi-swagger-2-0

Comment (steve-chavez) [reply sql/components.sql:70]: See https://postgrest.org/en/latest/references/api/preferences.html#prefer-params

Comment (laurenceisla) [reply sql/components.sql:70]: Cool, yeah, it should let us do that.

Comment (steve-chavez) [reply sql/components.sql:70]: :+1: If it's considerable work it can be left for another PR

Comment (laurenceisla) [reply sql/components.sql]: It's done. Only  adding the `deprecated` property is enough.
